'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('phone', {
  getState: () => ipcRenderer.invoke('phone:state'),
  command: (msg) => ipcRenderer.invoke('phone:command', msg),
  sendAudio: (pcm) => ipcRenderer.send('phone:audio', pcm),
  getAudio: () => ipcRenderer.invoke('phone:getAudio'),
  setAudio: (audio) => ipcRenderer.invoke('phone:setAudio', audio),
  getOptions: () => ipcRenderer.invoke('phone:getOptions'),
  setOptions: (options) => ipcRenderer.invoke('phone:setOptions', options),
  getAccounts: () => ipcRenderer.invoke('phone:accounts'),
  saveAccount: (data) => ipcRenderer.invoke('phone:saveAccount', data),
  deleteAccount: (id) => ipcRenderer.invoke('phone:deleteAccount', id),
  importPhonerLite: () => ipcRenderer.invoke('phone:importPhonerLite'),
  getRingtone: () => ipcRenderer.invoke('phone:getRingtone'),
  chooseRingtone: () => ipcRenderer.invoke('phone:chooseRingtone'),
  resetRingtone: () => ipcRenderer.invoke('phone:resetRingtone'),
  getVersion: () => ipcRenderer.invoke('phone:version'),
  openLog: () => ipcRenderer.invoke('phone:openLog'),
  getUpdate: () => ipcRenderer.invoke('phone:getUpdate'),
  installUpdate: () => ipcRenderer.invoke('phone:installUpdate'),
  onUpdate: (cb) => ipcRenderer.on('phone:update', (_e, version) => cb(version)),
  getContacts: () => ipcRenderer.invoke('phone:contacts'),
  saveContact: (data) => ipcRenderer.invoke('phone:saveContact', data),
  deleteContact: (id) => ipcRenderer.invoke('phone:deleteContact', id),
  importOutlook: () => ipcRenderer.invoke('phone:importOutlook'),
  importCsv: () => ipcRenderer.invoke('phone:importCsv'),
  exportCsv: () => ipcRenderer.invoke('phone:exportCsv'),
  onContacts: (cb) => ipcRenderer.on('phone:contactsChanged', (_e, list) => cb(list)),
  getHistory: () => ipcRenderer.invoke('phone:history'),
  clearHistory: () => ipcRenderer.invoke('phone:clearHistory'),
  onHistory: (cb) => ipcRenderer.on('phone:historyChanged', (_e, entries) => cb(entries)),
  onShowHistory: (cb) => ipcRenderer.on('phone:showHistory', () => cb()),
  onState: (cb) => ipcRenderer.on('phone:state', (_e, s) => cb(s)),
  onEnded: (cb) => ipcRenderer.on('phone:ended', (_e, reason) => cb(reason)),
  onAudio: (cb) => ipcRenderer.on('phone:audio', (_e, pcm) => cb(pcm)),
  onAudioFormat: (cb) => ipcRenderer.on('phone:audioFormat', (_e, fmt) => cb(fmt)),
  onInfo: (cb) => ipcRenderer.on('phone:info', (_e, text) => cb(text)),
});
